### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SouhadToukan** [alvaro-octal/TMDB-PHP-API#12]
Hello, i want to start using your project but i can't access the documentation.  The page in the link keeps on returning timeout error. If you could send the documentation to my email : souhad_toukan@hotmail.com that would be great ! Thanks a lot

**Comment by alvaro-octal** [comment]
Hi,

Now is available via http://pixelead0.github.io/tmdb_v3-PHP-API-/index.html  or http://alvaro-octal.github.io/TMDB-PHP-API/index.html

But this repo is mostly abandoned, please go to original https://github.com/pixelead0/tmdb_v3-PHP-API-
